# Configurazione tastiera (valori key SFML)
# freccia su=73, giu=74, sinistra=71, destra=72
# spazio=56, alt sinistro=39
KEY_UP=73
KEY_DOWN=74
KEY_LEFT=71
KEY_RIGHT=72
KEY_JUMP=39
KEY_SHOOT=56

# Configurazione Joystick (Assi: 0=X, 1=Y. Pulsanti: 0, 1, 2, 3...)
JOY_AXIS_X=0
JOY_AXIS_Y=1
JOY_JUMP=0
JOY_SHOOT=2